### ISSUE TITLE
Caso de Uso en papel: Registro de productos o materiales 

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#15]
El sistema deberá permitir la creación de códigos
El sistema debe permitir búsqueda de materiales por códigos, descripción del material y otros
El sistema debe permitir editar el lugar donde se encuentran los materiales lugares 
El sistema debe permitir editar el almacén  donde se encuentran los materiales

**Comment by camilolagrava** [comment]
![imagen9 (3)](https://user-images.githubusercontent.com/37836396/69804044-0e4e0100-11b4-11ea-80fa-5a137392c5ee.jpg)
