### ISSUE TITLE
Casos de uso en papel: Registro de Proveedores

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#16]
El sistema deberá permitir la adición, modificación
Considerando personas naturales, datos de identificación personal
También debe considerar personas jurídicas en cuyo caso debe registrarse la persona de contacto

**Comment by camilolagrava** [comment]
![imagen9 (2)](https://user-images.githubusercontent.com/37836396/69804084-258cee80-11b4-11ea-91bc-8ad7984e2298.jpg)
