### ISSUE TITLE
Caso de Uso en papel: Ingreso de materiales

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#17]
El sistema deberá permitir el registro de ingreso de materiales por el total o parcial según código de producto en catálogo.
El sistema debe permitir editar datos de la lista de materiales de un ingreso.

**Comment by camilolagrava** [comment]
![imagen1 (3)](https://user-images.githubusercontent.com/37836396/69804188-5f5df500-11b4-11ea-891a-f20ac7f92577.jpg)
