### ISSUE TITLE
Caso de uso en papel: Salida de materiales

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#18]
El sistema deberá de registrar la salida de materiales al funcionario solicitante
El sistema debe permitir editar datos de la lista de materiales de una salida.

**Comment by camilolagrava** [comment]
[https://github.com/Hutini/Hutini/blob/master/makups%20y%20demas/imagen3.jpg](url)

**Comment by camilolagrava** [comment]
>
![imagen3](https://user-images.githubusercontent.com/37836396/69803790-73552700-11b3-11ea-936f-6bdb7f878a0d.jpg)
