### ISSUE TITLE
Caso de uso en papel: Recuento de Almacén

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#19]
El sistema debe permitir registrar o programar la realización de un recuento físico de materiales o productos de un almacén, a un determinado usuario como supervisor para que realice tal tarea.
El sistema permitirá al usuario realizar una consulta sobre el estado de saldos de las diferentes bodegas después de realizar un recuento en cada bodega

**Comment by camilolagrava** [comment]
![imagen4](https://user-images.githubusercontent.com/37836396/69804294-9b915580-11b4-11ea-9f32-6bc719454abf.jpg)
