### ISSUE TITLE
Caso de uso enpapel: Alertas del sistema 

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#20]
El sistema deberá de emitir alertas de stock mínimo

**Comment by camilolagrava** [comment]
![imagen9 (4)](https://user-images.githubusercontent.com/37836396/69804357-c4194f80-11b4-11ea-84f6-fd116a557fff.jpg)

**Comment by camilolagrava** [comment]
![imagen10 (2)](https://user-images.githubusercontent.com/37836396/69804407-dc896a00-11b4-11ea-804a-6823c93ab0b9.jpg)
