### ISSUE TITLE
Caso de uso en papel: Control de Materiales

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#21]
El sistema permitirá registrar control de inventario físico total o parcial, permitiendo comparar cantidad de materiales registrados en el sistema con cantidad de materiales verificados físicamente, anotando observaciones en caso de faltantes o sobrantes.

**Comment by camilolagrava** [comment]
![imagen15](https://user-images.githubusercontent.com/37836396/69805697-941f7b80-11b7-11ea-942a-378936d10dda.jpg)
