### ISSUE TITLE
Caso de uso en papel: Consultas y Listados 

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#22]
Estado de Saldos, permitirá al usuario realizar una consulta sobre el estado de saldos de las diferentes bodegas según vayan registrándose los ingresos y salidas del almacén

**Comment by camilolagrava** [comment]
![imagen16](https://user-images.githubusercontent.com/37836396/69805712-9eda1080-11b7-11ea-9eb5-1be453a6446b.jpg)
