### ISSUE TITLE
Caso de uso en papel: Reportes

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#23]
Reporte de Registros de Ingresos de Compras, donde el usuario podrá generar reportes que visualiza de manera ordenada los registros de ingresos de materiales a un almacén  o todos los almacenes en un lapso determinado de tiempo. 
Reporte Detallado de Ingresos por Compras, donde el usuario podrá generar reportes que visualiza de manera detallada los ingresos por cada una de las compras que se registraron en  almacenes o un determinado almacén 
Reportes sobre Saldos en Almacén, donde el usuario podrá generar reportes que visualiza de manera resumida los saldos generados en cada bodega dentro en un lapso determinado de tiempo dado un lapso determinado de tiempo.

**Comment by camilolagrava** [comment]
![imagen5](https://user-images.githubusercontent.com/37836396/69804493-1490ad00-11b5-11ea-878d-9cde7a8a39b7.jpg)
