### ISSUE TITLE
Arquitectura de front-end Diagrama Tecnologías

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#35]

**Comment by tamikaivi** [comment]
![Arquitectura Front-end](https://user-images.githubusercontent.com/37809586/69768669-cb5e4000-1157-11ea-8045-e4856f43021a.png)

**Comment by tamikaivi** [comment]
Version 8 de Android

**Comment by sergiotorricol** [comment]
Esta es la última arquitectura front-end.
