### ISSUE TITLE
Arquitectura de back-end Diagrama Tecnologías

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#36]

**Comment by tamikaivi** [comment]
![Arquitectura BAck-End](https://user-images.githubusercontent.com/37809586/69830589-ec786c80-11fb-11ea-80e9-f30f1b34450e.png)

**Comment by tamikaivi** [comment]
que es Json

**Comment by tamikaivi** [comment]
java con sqlite

**Comment by tamikaivi** [comment]
poner imagen base de datos

**Comment by tamikaivi** [comment]
Rest Json

**Comment by sergiotorricol** [comment]
Esta es la última arquitectura back-end.
