### ISSUE TITLE
Introducción de Arquitectura de Software

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#37]

**Comment by camilolagrava** [comment]
Toda arquitectura de software debe describir diversos aspectos del software. Por lo general, estos suelen ser complejos de entender y de descifrar. Los siguientes diagramas se enfocaran en dar explicación  a las tecnologías encargadas de la interfaz como el engine, ademas de generalidad, que utilizará la arquitectura de software del proyecto propuesto para el SISTEMA DE INVENTARIO PARA :  EL GOBIERNO AUTÓNOMO DEPARTAMENTAL DE ORURO - SECRETARIA DEPARTAMENTAL DE ADMINISTRACIÓN Y FINANZAS PÚBLICAS – ÁREA PROVISIÓN Y DOTACIÓN BIENES Y SERVICIOS - SECCIÓN ALMACENES.

**Comment by camilolagrava** [comment]
Toda arquitectura de software debe describir diversos aspectos del software. Por lo general, estos suelen ser complejos de entender y de descifrar. Los siguientes diagramas se enfocaran en dar explicación a las tecnologías encargadas de la interfaz como el engine, ademas de dar una breve explicación a la generalidad, que utilizará la arquitectura de software del proyecto propuesto para el SISTEMA DE INVENTARIO PARA : EL GOBIERNO AUTÓNOMO DEPARTAMENTAL DE ORURO - SECRETARIA DEPARTAMENTAL DE ADMINISTRACIÓN Y FINANZAS PÚBLICAS – ÁREA PROVISIÓN Y DOTACIÓN BIENES Y SERVICIOS - SECCIÓN ALMACENES.
