### ISSUE TITLE
Introducción de Mockup en la wiki

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#39]

**Comment by camilolagrava** [comment]
Un mockup un modelo a escala de un diseño , utilizado para la demostración, evaluación del diseño. Un mockup es un prototipo si proporciona al menos una parte de la funcionalidad de un sistema y permite pruebas del diseño. Los mockups son utilizados  para la adquisición de comentarios por parte de los usuarios.
Los siguientes mockups pertenecen a  EL SISTEMA DE INVENTARIO PARA : EL GOBIERNO AUTÓNOMO DEPARTAMENTAL DE ORURO - SECRETARIA DEPARTAMENTAL DE ADMINISTRACIÓN Y FINANZAS PÚBLICAS – ÁREA PROVISIÓN Y DOTACIÓN BIENES Y SERVICIOS - SECCIÓN ALMACENES. 
Con el objetivo de dar visibilidad a , la general, funcionalidad del sistema en sí.
