### ISSUE TITLE
Definir si la aplicación es Mobile o Web

### ISSUE THREAD

**Issue by hrnn** [Hutini/Hutini#4]

**Comment by camilolagrava** [comment]
Estamos estimando la posibilidad de de crear la app para escritorio, gracias a los objetivos que podemos ver en la documentación

**Comment by tamikaivi** [comment]
Preguntar si podemos hacer una aplicación para escritorio o solo se puede escoger entre web y mobile

**Comment by tamikaivi** [comment]
El proyecto sera una app Móvil
