### ISSUE TITLE
Seleccionar que proyecto realizar en el curso

### ISSUE THREAD

**Issue by hrnn** [Hutini/Hutini#5]

**Comment by tamikaivi** [comment]
Se ha analizado y realizado lectura a los proyectos propuestos

**Comment by tamikaivi** [comment]
Volvimos a buscar mas proyectos por la poca información de requerimientos que tenia el proyecto que queríamos

**Comment by tamikaivi** [comment]
Encontramos un proyecto  17-1302-00-773962-2-1 Contratacion De Consultoria Por Producto Para El Desarrollo De Software Administrativo De Cobros Para Emapaq

**Comment by tamikaivi** [comment]
Estamos leyendo toda la documetación del proyecto que escogimos

**Comment by tamikaivi** [comment]
Buscamos que es EMAPAQ La Empresa Autónoma Municipal de Agua Potable y Alcantarillado Sanitario de Quillacollo “EMAPAQ”, es una entidad pública desconcentrada, con tramites de personalidad jurídica y patrimonio propios, proponiendo una autonomía de gestión operativa y administrativa, sujeta a fiscalización por el H. Concejo Municipal de Quillacollo y al control social, a través de las organizaciones sociales, conforme a la Ley, cuya finalidad es dedicarse, por cuenta propia o ajena, mancomunada o asociada con terceros, a la administración y prestación de servicios de agua potable y alcantarillado sanitario con calidad y continuidad, así como a ejecutar obras de mejoramiento de los sistemas de agua potable y alcantarillado y sistemas de operación y mantenimiento de equipos e infraestructura que componen los sistemas de servicios de agua potable y alcantarillado sanitario y otros, relacionados con los servicios de agua potable y alcantarillado sanitario dentro del ámbito de su jurisdicción, en el marco de las Licencias y Registros, previstos por Ley.

Esta situación es ratificada asimismo mediante Ley 2066 de Agua Potable y Alcantarillado Sanitario donde en sus artículos 13 y 17, se especifica que es de responsabilidad de los Gobiernos Municipales, en el ámbito de su jurisdicción, el asegurar la provisión de Servicios de Agua Potable y Alcantarillado Sanitario, a través de una Entidad Prestadora de Servicios de Agua Potable y Alcantarillado Sanitario (EPSA).

**Comment by tamikaivi** [comment]
Que es otb?

**Comment by tamikaivi** [comment]
cuales son los estados de usuario?

**Comment by tamikaivi** [comment]
no entendemos a que se refiere fichas descriptivas 
REPORTES.: Le permite ver e imprimir reportes al usuario. Reportes como: 
•	Reporte de contribuyentes
•	Fichas descriptivas de contribuyente 
•	Reporte de deudores
•	Reporte deudores por zona, otb
•	Reportes de ingresos por periodos, diarios
•	Reporte de seguimiento de pagos por usuario
•	Reporte por orden alfabético de usuarios
•	Reporte por orden correlativo de código de usuario o medidor.

**Comment by tamikaivi** [comment]
No se detalla quienes son los usuarios
USUARIOS:  Permitirá definir usuarios y tipos de usuarios según roles definidos para que puedan hacer uso del sistema. 
•	Registro de roles
•	Asignacion de usuario a un rol
•	Creacion de perfiles de usuario

**Comment by tamikaivi** [comment]
No se detalla quienes son los usuarios
USUARIOS:  Permitirá definir usuarios y tipos de usuarios según roles definidos para que puedan hacer uso del sistema. 
•	Registro de roles
•	Asignacion de usuario a un rol
•	Creacion de perfiles de usuario

**Comment by tamikaivi** [comment]
A los efectos de la Ley 1551 de Participación Popular, se entiende por Organización Territorial de Base, la unidad básica de carácter comunitario o vecinal que ocupa un espacio territorial determinado, comprende una población sin diferenciación de grado de instrucción, ocupación, edad, sexo o religión y guarda una relación principal con los órganos públicos del Estado a través del Gobierno Municipal de la jurisdicción donde está ubicada.

**Comment by tamikaivi** [comment]
2. 19-0139-00-958711-0-E
Desarrollo Del Sitio Web: Espaã?Ol De La Facultad De Arquitectura

3. 17-0905-00-800018-0-E
Diseño De Pagina Web Para El Gobierno Autónomo Departamental De Potosí

**Comment by tamikaivi** [comment]
No especifica el porcentaje de de cobro
	6. PARAMETROS:  Le permite definir los valores para que el sistema funcione, así mismo estos valores solo pueden ser manipulados por el administrador del sistema.   Datos como registro de ufv, categoría, registro periodos, etc. 
•	Registro de ufv
•	Registro de categorías de cobro (asociado porcentaje de cobro por lectura)
•	Cálculo del impuesto (Puede no ser una vista sino cálculos internos)
•	Registro de periodos de cobro

**Comment by tamikaivi** [comment]
Nuevo proyecto:
19-0904-00-986711-2-1 
CONTRATACION DE SERVICIO DE CONSULTORIA POR PRODUCTO PARA EL DESARROLLO DE UN SISTEMA DE ALMACENES – GOBIERNO AUTONOMO DEPARTAMENTAL DE ORURO

**Comment by tamikaivi** [comment]
Que es SABS Sistema de administración de Bienes y Servicios

**Comment by tamikaivi** [comment]
Solicitud de salida de materiales SABS-1

**Comment by tamikaivi** [comment]
que son inventario peps? Manejo de inventarios PEPS

**Comment by tamikaivi** [comment]
que es Integración a SIGAPO?

**Comment by tamikaivi** [comment]
Cuales con los saldos?
Cierre y apertura de gestión
El sistema deberá permitir el cierre de gestión con saldos finales.
El sistema deberá permitir iniciar nueva gestión con saldos iniciales.
El sistema deberá impedir cambiar datos de gestiones anteriores cerradas.
El sistema ofrecerá posibilidad de consultar datos y reportes de gestiones anteriores

**Comment by tamikaivi** [comment]
No especifica el formato del Excel
Importación de Índices UFVs..
El sistema permitirá importar archivo Ms.EXCEL en base a un formato dado, la incorporación de valores de UFVs para un gestión dada de los 365 días del año.
El sistema ofrecerá posibilidad de ingresar valor de UFV de una fecha dada, semana o mes, o año de manera amigable y fácil de actualizar.
El sistema deberá exportar a MS. EXCEL tabla anual de valores de UFVs para ser cargados en el sistema.

**Comment by tamikaivi** [comment]
Arquitectura 
El sistema tendrá una estructura modular orientado a servicios que soporte adición gradual de componentes o subsistemas.
