### ISSUE TITLE
Crear el proyecto inicial.

### ISSUE THREAD

**Issue by sergiotorricol** [Hutini/Hutini#52]
Crear el proyecto inicial.
Como desarrollador
Quiero  crear el proyecto inicial
Para poder empezar a programar

**Comment by tamikaivi** [comment]
La idea es que cada persona se encargue que funcione cada caso de uso 
haciendo su interfaz gráfica back-end y base de datos para no atrasarnos 
@sergiotorricol @camilolagrava

**Comment by camilolagrava** [comment]
Ya terminé con los layouts que me encargarin
