### ISSUE TITLE
Crear un repositorio de Prueba.

### ISSUE THREAD

**Issue by sergiotorricol** [Hutini/Hutini#53]
Crear un repositorio.
Como desarrollador
Quiero crear un repositorio de prueba
Para poder empezar a codear el hello world

**Comment by tamikaivi** [comment]
Ya he creado el repositorio para hacer el hello @sergiotorricol  @camilolagrava se llama codigo prueba

**Comment by tamikaivi** [comment]
ya esta el repositorio
@sergiotorricol  @camilolagrava es el que dice hello world clonenlo crean un branch esciiben un hello world y lo suben a sus branches y luego depues de comentar recien lo sbern al master
