### ISSUE TITLE
Hacer el poker planning 

### ISSUE THREAD

**Issue by camilolagrava** [Hutini/Hutini#54]
Descripción: Crear y repartir las dificultades para los user story.

Como: Desarrollador.
Quiero: hacer la dinámica (poker planning).
Para:  Para  priorizar las tareas y estimar el tiempo de los issues.

**Comment by camilolagrava** [comment]
Poner el link de poker planning en comentarios

**Comment by tamikaivi** [comment]
https://play.planningpoker.com/play/game/BkvNwhIfi3rDKBrpvSdFpdf6mvPy7qlc
Aqui esta el link del poker planing

**Comment by tamikaivi** [comment]
crear proyecto inicia 3

**Comment by camilolagrava** [comment]
Crear un repositorio 3

**Comment by sergiotorricol** [comment]
Hacer el repositorio obtuvo un 0 en el poker planning

**Comment by tamikaivi** [comment]
crear branches 5

**Comment by camilolagrava** [comment]
Subir un Hello Word 5
