### ISSUE TITLE
Crear branches

### ISSUE THREAD

**Issue by sergiotorricol** [Hutini/Hutini#55]
Descripción: Todos los colaboradores deben de crear usus propios branches para el proyecto.
Como desarrolador
Quiero crear branches
Para subir el código y acostumbrarse con las herramientas.

**Comment by tamikaivi** [comment]
Solo es para hacer la prueba para saber si nos funciona

**Comment by tamikaivi** [comment]
https://www.youtube.com/watch?v=d6G7nT6bhwc

**Comment by tamikaivi** [comment]
ya hice mi branch pero no no lo uni al branch master

**Comment by camilolagrava** [comment]
Ya hice ya hice un bran pero no un pull request
