### ISSUE TITLE
Prueba: Pull y Push

### ISSUE THREAD

**Issue by camilolagrava** [Hutini/Hutini#58]
Descripcion: Pull o clonar el proyecto  y puchearlo.
Como: Desarrollador.
Quiero: Hacer las funciones basicas de un proyecto compartido.
Para: Recordar y familiarizarnos con las herramientas de gitHub y andriodStudio.

**Comment by tamikaivi** [comment]
https://www.youtube.com/watch?v=NIp7yGxf30I
Para emular en el celular
