### ISSUE TITLE
Definir quienes usaran la aplicación

### ISSUE THREAD

**Issue by hrnn** [Hutini/Hutini#6]
quienes son los usuarios

**Comment by tamikaivi** [comment]
Persona jurídica (o persona moral) es un individuo con derechos y obligaciones que existe, pero no como persona física, sino como institución que es creada por una o más personas físicas para cumplir un objetivo social que puede ser con o sin fines de lucro.

**Comment by tamikaivi** [comment]
JERARQUIA DE USUARIOS
USUARIO MAESTRO.- Puede tener control total del sistema de almacenes.
USUARIO ADMINISTRADOR.- Tienes la opción de ABM de usuarios, además de modificar actualizar los datos ingresados por los usuarios de almacenes, podrá validar los reportes y otra información generada.
USUARIO ALMACENES.- Deberá realizar ingreso, salida movimiento préstamo de material y otros según lo indicado anteriormente.
USUARIO CONTABILIDAD.- Podrá emitir informes y adicionar información de acuerdo a requerimiento del área.

**Comment by tamikaivi** [comment]
Todos los usuarios del sistema tendrán posibilidad de cambiar contraseña secreta de acceso al sistema.
El sistema deberá soportar la incorporación de imagen o fotografía de cada usuario.

**Comment by tamikaivi** [comment]
GOBIERNO AUTONOMO DEPARTAMENTAL DE ORURO
SECRETARIA DEPARTAMENTAL DE ADMINISTRACION Y FINANZAS PÚBLICAS – AREA PROVISION Y DOTACION BIENES Y SERVICIOS - SECCION ALMACENES
