### ISSUE TITLE
Cambio de tecnologias

### ISSUE THREAD

**Issue by tamikaivi** [Hutini/Hutini#80]
Descripción: Cambio de tecnologías
como : desarrolladores 
queremos: definir el cambio de tecnologias
para: poder avanzar en el proyecto

**Comment by tamikaivi** [comment]
@camilolagrava ya hice el issue

**Comment by camilolagrava** [comment]
ahora mismo estoy instalandome node.js para crear servicios y servidores

**Comment by tamikaivi** [comment]
yo estoy viendo sijava script se necesita intlar algo mas

**Comment by tamikaivi** [comment]
https://www.youtube.com/watch?v=ranSYb-EhrU

**Comment by camilolagrava** [comment]
https://youtu.be/BhvLIzVL8_o

este es node desde cero

**Comment by tamikaivi** [comment]
https://www.youtube.com/watch?v=khCIunNAEHI
este es el tutorial que tenemos que seguir
